# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: mitre.fhir.hm.pdr
canonical: https://github.com/Open-Health-Manager/patient-data-receipt-ig
name: HealthDataReceipt
status: draft
version: 0.2.0
fhirVersion: 4.0.1
copyrightYear: 2022+
releaseLabel: ci-build
license: CC0-1.0
publisher:
  name: Health Manager
  url: https://mitre.sharepoint.com/sites/healthmanager

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Use Cases: usecases.html
  Specification:
    Implementation: implementation.html
    Connectathons: connectathon.html
  Artifacts: artifacts.html

# ╭───────────────────────────────────────package-list.json────────────────────────────────────────╮
# │  To control the package-list.json using this config, uncomment and set the "history" property. │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯

resources:
  Bundle/pdr-message:
    name: PDR Message Example
    description: Example of a full patient data receipt message
  Procedure/pdr-create-colonoscopy:
    name: PDR RESTful Create Example
    description: Example of a RESTful create of an individual procedure as a patient data receipt
